### PR TITLE
chore setup testing and CI environment

### PR DESCRIPTION
**Pull request by 41hulk**
#### What does this PR do?
Configured the testing environment and Continuous Integration

#### Description of Task to be completed?
-install mocha,chai and sinon
-test /api endpoint
-configured Travis CI 
-Coveralls for coverage checking 

#### How should this be manually tested?
run: ```npm run test```
run:```nom run coverage```

#### What are the relevant pivotal tracker stories?
tracker: ```6Prv9VNn```
#### Screenshots 
Screen Shot 2020-11-16 at 9 39 06 PM
Screen Shot 2020-11-16 at 10 21 18 PM
Screen Shot 2020-11-16 at 10 21 58 PM

### CODE REVIEW

**Review by mansurissa — CHANGES_REQUESTED** [review]
Please add description to your PR

**Review by samuel776 — COMMENTED** [review]
as Issa said you should add description to you PR

**Comment by 41hulk** [comment]
@mansurissa and @samuel776 Done with the requested changes

**Review by samuel776 — APPROVED** [review]

**Review by GuevaraMarius — APPROVED** [review]

**Review by KundwaBruno — APPROVED** [review]

**Review by mansurissa — APPROVED** [review]
Well done

**Pull request merged**
