### PR TITLE
6Prv9VNn adding procfile and README

### PR DESCRIPTION
**Pull request by samuel776**
#### What does this PR do?
          This PR serves to configure the Heroku pipeline on Heroku and code climate
#### Description of Task to be completed?
          -configuration of Heroku CLI
          -creating procfile
          -Hosting the app on Heroku
          -configuration of code climate for code analysis
#### How should this be manually tested?
          -clone repo
          -npm install
#### What are the relevant  trello stories?
          6Prv9VNn 
#### Screenshots (if appropriate)

image
image

### CODE REVIEW

**Review by SIBONIYO — APPROVED** [review]
Good Job

**Review by Egide138 — APPROVED** [review]

**Review by mansurissa — APPROVED** [review]
good job

**Review by KundwaBruno — APPROVED** [review]

**Review by 41hulk — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
Use [this](https://github.com/andela/octopus-bn-backend) template to see what needs to be added to README.

**Review by GuevaraMarius — APPROVED** [review]

**Comment by samuel776** [comment]
i have managed to work on the changes requested, i hope it is ready to be merged if it meets all required

**Review by ceelogre — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
`nodemon` is a development tool, when we move to production, the app must be run with `node`

**Review by ceelogre — CHANGES_REQUESTED** [review]
Remove the procfile, create a build pipeline using ` "build": "babel -d ./build ./src"` then change your start script to `node ./build`

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
